# Inventory для Kubespray.
#
# Как заполнить:
#   ansible_host  = ПУБЛИЧНЫЙ IP ноды (из `terraform output k8s_nodes_ips`, поле public_ip)
#   ip            = ПРИВАТНЫЙ IP ноды (поле private_ip)
#   ansible_user  = ubuntu
#
# Скопируйте этот файл в inventory/mycluster/inventory.ini склонированного Kubespray.
# IP ниже — ПРИМЕР, подставьте свои значения после `terraform apply`.

[all]
master1 ansible_host=93.77.176.75 ip=192.168.1.23 etcd_member_name=etcd1 ansible_user=ubuntu
worker1 ansible_host=89.169.187.246 ip=192.168.2.4 ansible_user=ubuntu
worker2 ansible_host=158.160.220.243 ip=192.168.3.21 ansible_user=ubuntu

[kube_control_plane]
master1

[etcd]
master1

[kube_node]
worker1
worker2

[k8s_cluster:children]
kube_control_plane
kube_node
